### ISSUE TITLE
error: Symbol’s value as variable is void: project-directory

### ISSUE THREAD

**Issue by wuqui** [quarto-dev/quarto-emacs#1]
I just wanted to try Quarto in Emacs, but when I run `quarto-preview` I get the following error:

```
funcall-interactively: Symbol’s value as variable is void: project-directory
```

When I run `quarto render` from shell on the same file, it works fine.

By the way, Quarto looks really, really promising. I'm looking forward to using it and hoping it will bring about some unification for the R vs Python and  `.ipynb` vs `.md` communities :)

**Comment by sje30** [comment]
I get the same error.

As a workaround 
```
(setq project-directory nil)
```
evaluate that globally, or in the .qmd buffer.

**Comment by cscheid** [comment]
Apologies for the delayed reply - my github settings weren't sending notifications for this. I just fixed this and pushed a new version to melpa. Sorry about the inconvenience!
