### ISSUE TITLE
Can't find quarto-mode

### ISSUE THREAD

**Issue by onurcanbektas** [quarto-dev/quarto-emacs#2]
I installed this package via the interactive method

```
M-x package-install
quarto-mode
```
I restarted emacs, but when I type `M-x` I can't find `quarto-mode` as an available mode, even when I open a .qmd document.

**Comment by losttenko** [comment]
Having the same issue

**Comment by sje30** [comment]
What happens if you try to open a new buffer, e.g. 'a.qmd'?

For me, it opens in Markdown and Quarto mode thanks to polymode.

Do you have polymode installed?

If so, you should see 'poly-quarto-mode' is defined.  I don't think there is a 'quarto-mode' defun.

**Comment by cscheid** [comment]
I've updated the `README.md` to reflect this. Sorry about the confusion, and please feel free to reopen the issue if this still doesn't work for you.
