### ISSUE TITLE
ess lsp breaks cursor outside of code blocks

### ISSUE THREAD

**Issue by iod-ine** [quarto-dev/quarto-emacs#6]
I have a very interesting problem in `qmd` files. After the cursor enters any R code (Python doesn't do that), either in a block or inline, the LSP process starts and enables all the IDE functionality when the cursor is in code. Code editing works great. However, something insane starts to happen outside the code, when I try to add any text: the cursor jumps around and renders the whole buffer unusable unless it finds itself within R code. The only way to get back to writing markdown is to kill and reopen the buffer, and by all means avoid accidentally touching code.

Here is the file that I am working with right now. It's a part of a project, so there is no header. I indented the code block to escape from the GitHub interpreter.

```markdown
# Inventory data

I have access to two field inventory datasets with overlapping UAV ALS and multispectral measurements.

    ```{r}
    #| label: setup
    #| include: false

    library(sf)
    library(DBI)
    library(tmap)

    connection <- dbConnect(
      drv = RPostgres::Postgres(),
      host = "localhost",
      dbname = "trees"
    )

    trees1 <- read_sf(connection, Id(schema = "stands", table = "trees1"))
    trees2 <- read_sf(connection, Id(schema = "stands", table = "trees2"))
    ```

## First polygon

It has total `r nrow(trees1)` trees.
```

After the cursor has touched code, it seems to jump to the beginning of the last line of the document after every keystroke in insert mode. If it's already at the end, the text is being inverted like this `!?gnineppah si kceh eht tahW`. When on the line with inline code, sometimes instead of jumping to the end of the buffer, it jumps to the end of the inline code, before the closing backtick. Typing the backtick does something that I don't even know how to describe, everything moves and the current line partly consumes the line above. Sometimes it randomly stops doing all that for the part of the file below the code block, but any action above it moves the cursor to the first line of the block.

I am very new to Emacs, and I don't even know where to start looking to debug and fix this. I use Doom Emacs, so there might be some configuration clash that I can't think of yet. I would appreciate any guidance greatly!

**Comment by cscheid** [comment]
We don't run an LSP on quarto-emacs, so I suspect something from Doom Emacs is taking over control of your buffer.

**Comment by iod-ine** [comment]
@cscheid I disabled LSP for ESS and everything is fixed. I thought LSP was a requirement, thank you for clarifying!
