### ISSUE TITLE
void-function poly-quarto-mode

### ISSUE THREAD

**Issue by gdkrmr** [quarto-dev/quarto-emacs#8]
When loading `qmd` files I get the following error:

```
File mode specification error: (void-function poly-quarto-mode)
```

- qmd files are associated with `poly-quarto-mode`.
- I am using Spacemacs, not sure if this has anything to do with it. 
- `Rmd` files work just fine and quarto mode also works just fine after I manually evaluate `quarto-mode.el`.
- the quarto-mode directory is in `load-path`

**Comment by gdkrmr** [comment]
I have solved it: Spacemacs users need to put `(require 'quarto-mode)` inside their `dotspacemancs/user-config`

**Comment by eddelbuettel** [comment]
FWIW I needed it on GNU Emacs too to have a .qmd file associated with the mode.

**Comment by cscheid** [comment]
@eddelbuettel I'm just going to add this to the README.

**Comment by Kodiologist** [comment]
Isn't there a way that Emacs provides for packages to be loaded automatically once a file that requires the corresponding major mode is visited? Then Emacs won't need to load this package unless it's actually needed.

**Comment by cscheid** [comment]
@Kodiologist I believe you're talking about autoload, which [we do use](https://github.com/quarto-dev/quarto-emacs/blob/main/quarto-mode.el#L52-L66).

**Comment by Kodiologist** [comment]
So then shouldn't autoload trigger in place of the original error "void-function poly-quarto-mode"?

**Comment by cscheid** [comment]
I mean, yes, but I believe the user report. If you understand what's happening, I'd love to hear it.

**Comment by Kodiologist** [comment]
No idea. I got to this GitHub issue because I had the same error. Evidently there's some subtlety to Emacs package management I don't understand. If the error can be easily reproduced with a clean Emacs, this issue should probably be reopened.
